// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import users "github.com/vaksi/user_management/internal/users"

// UserRepositoryFactory is an autogenerated mock type for the UserRepositoryFactory type
type UserRepositoryFactory struct {
	mock.Mock
}

// Store provides a mock function with given fields: _a0
func (_m *UserRepositoryFactory) Store(_a0 *users.UserModel) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*users.UserModel) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
