version: "2.3"
services:
  mysql:
    container_name: mysql_messaging
    image: mysql:5.7
    volumes:
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - 33060:3306
    environment:
      - MYSQL_DATABASE=messaging
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - backend
  app:
    container_name: messaging_app
    build: .
    restart: always
    ports:
      - 8081:8081
    networks:
      - backend
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
networks:
  backend: