// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserServiceFactory is an autogenerated mock type for the UserServiceFactory type
type UserServiceFactory struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: email, fullName, gender
func (_m *UserServiceFactory) CreateUser(email string, fullName string, gender int8) error {
	ret := _m.Called(email, fullName, gender)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int8) error); ok {
		r0 = rf(email, fullName, gender)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
